config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :songs, only: [:create, :index]
      resources :playlists, only: [:index, :create]
      resources :users, only: [:index, :show]
      resources :individuals, only: [:create, :show]

    end
  end

  root 'playlists#index'
  resources :playlists, only: [:index, :show]
  resources :homes, only: [:index, :new, :create]

  resources :favorites, only: [:index]
  resources :individuals, only: [:index, :show, :edit, :update, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord

  belongs_to :user
end

app/models/individual.rb
class Individual < ApplicationRecord

  belongs_to :user
  validates :name, presence: true
  validates :first_song, presence: true
  validates :list, presence: true


end

app/models/playlist.rb
class Playlist < ApplicationRecord
before_validation(on: :create)

  validates :name, presence: true
  validates :playlist_id, presence: true
end

app/models/search.rb
class Search < ApplicationRecord

  def self.search(query)
    where("name ilike ?", "%#{query}%")
  end

end

app/models/song.rb
class Song < ApplicationRecord

belongs_to :user

validates :name, presence: true
validates :youtube_id, presence: true
validates :youtube_id, uniqueness: { scope: :user_id }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  has_many :songs
  has_many :individuals
  has_many :homes

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, length: { minimum: 4, maximum: 16 }
  validates :username, format: { with: /\A(?!.*\.\.)(?!.*\.$)[^\W][\w.]{0,17}\z/,
    message: "can only contain characters a-z, 0-9, underscores and periods" }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :encrypted_password, length: { minimum: 6 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


   def name
   first_name + " " + last_name
   end
end

app/controllers/api/v1/individuals_controller.rb
class Api::V1::IndividualsController < ApplicationController
  respond_to :json
  skip_before_filter :verify_authenticity_token



  def show

    individual = Individual.find(params[:id])


    respond_with individual
  end



  def create
    body = request.body.read
    parsed = JSON.parse(body)
    
    individual = Individual.new(parsed)

    individual.user_id = current_user.id


    if individual.save
      flash[:success] = "View profile to see your newly saved song!"
    else
       flash[:errors] = song.errors.full_messages.join(',')

    end

  end

end

app/controllers/api/v1/playlists_controller.rb
class Api::V1::PlaylistsController < ApplicationController
  respond_to :json
  skip_before_filter :verify_authenticity_token

  def index
    if params[:id]
      playlist = Playlist.find(params[:id])
      respond_with playlist
    else
      playlists = Playlist.all
      render json: playlists
    end
  end

  def create
    body = request.body.read
    parsed = JSON.parse(body)
    playlist = Playlist.new(parsed)

    playlist.user_id = current_user.id


    if playlist.save


      flash[:success] = "Platlist added succsessfully"
    else
       flash[:errors] = playlist.errors.full_messages.join(',')

    end

  end

end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @sites = Site.all
    if params[:query]
      query = params[:query]
      @sites = Site.where("name ilike ?", "%#{query}%")
      render json: @sites
    else
      @sites = Site.all.order("created_at DESC")
    end
  end

  private

  def search_params
    params.permit(:query)
  end

end

app/controllers/api/v1/songs_controller.rb
class Api::V1::SongsController < ApplicationController
  respond_to :json
  skip_before_filter :verify_authenticity_token



  def create
    body = request.body.read
    parsed = JSON.parse(body)
    song = Song.new(parsed)

    song.user_id = current_user.id


    if song.save
      render json: {message: ["#{song.name} has been saved!"]}

    else
       render json: {message: ["You have already liked this song"]}

    end

  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def index
    user = User.find(current_user.id)


    render json: user
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authorize_user, only: [:index]
  def index

  end

  def new
    @home = Home.new
  end

  def create

    if current_user == nil
      flash[:message] = "You need to be signed in to request Admin access."
      redirect_to new_user_session_path
    else
      @home = Home.new(homes_params)
      @home.user_id = current_user.id

      if @home.save

      
        AdminMailer.new_admin(@home)

        flash[:message] = "You're request to become an Admin has succesfully been sent!"
        redirect_to root_path
      else
        flash[:errors] = @home.errors.full_messages.join(', ')
        redirect_to new_home_path
      end
    end

  end

  def authorize_user
   if !user_signed_in? || current_user.admin == false
     redirect_to new_home_path
   end
 end


 private
 def homes_params
   params.require(:home).permit(:name, :body)
 end
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  def index

  end

  def show
  end

  def edit
    @individual = Individual.find(params[:id])

  end

  def update
    @individual = Individual.find(params[:id])
    new_individual = @individual.update_attributes(individual_params)
    render :show

  end

  def destroy
    @individual = Individual.find(params[:id])
    @individual.destroy
    redirect_to individuals_path
  end

  private
  def individual_params
    params.require(:individual).permit(:name, :first_song, :list)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/index.html.erb
<div id="profile">




</div>

app/views/homes/index.html.erb
<div id="home">




</div>

app/views/homes/new.html.erb
<h3>You need to be an admin before you can submit playlists</h3>


<div class="adminForm">



  <%= form_for @home do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :body, "Why do you think you should be an admin?" %>
      <%= f.text_area :body %>
    </div>

    <div class="actions">
      <%= f.submit "Submit", class: "button" %>
    </div>
  <% end %>

</div>

app/views/individuals/edit.html.erb
<h1>Edit Playlist</h1>
<%= form_for [@individual] do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Update Name", class: "button"%>
  </div>
<% end %>

app/views/individuals/index.html.erb
<div id="individuals">

</div>

app/views/individuals/show.html.erb
<h5><%= link_to "Delete Playlist", @individual, method: :delete, data: {confirm: "Are you sure?"} %> </h5>

<div id="individual">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />



    <title><%= content_for?(:title) ? yield(:title) : "Looting For Ears" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller_name %>">
    <% flash.each do |type, message| %>
    <div class="<%= "flash #{type}" %>">
       <%= message %>
    </div>
  <% end %>
    <div class="top-bar">
    <div class="top-bar-left">
      <ul class="menu">
        <li><%= link_to "Curated Playlists", playlists_path %></li>
        <li><%= link_to "Personal Playlists", individuals_path %></li>
        <li>    <%= link_to "Submit Playlist", homes_path %>     </li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <% if signed_in? %>
          <li><%= current_user.name %></li>
          <li>  <%= link_to "Favorite Songs", favorites_path %>    </li>
          <li>  <%= link_to "Edit Profile", edit_user_registration_path %>  </li>
          <li><%= link_to "Sign out", destroy_user_session_path, data: { method: 'delete' } %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Join", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

    <%= yield %>

  </body>
</html>

app/views/playlists/index.html.erb
<div id="playlist">
  Looting for Ears

</div>

app/views/playlists/show.html.erb
<div id="looting">
  Looting for Ears

</div>